### ISSUE TITLE
Wrong period calculation for leap years.

### ISSUE THREAD

**Issue by cage200** [JodaOrg/joda-time#295] opened 2015-06-24 09:59 UTC
First of all , thank you for a great library and for your contribution to JDK 8.

I have a problem with yoda  time library only for a specific situation.
The code below will calculate a period of 3 years and 12 months.

        DateTime leapday = new DateTime(1996, 2, 29, 0, 0, 0, 0);
        DateTime febof28year2000 = new DateTime(2000, 2, 28, 0, 0, 0, 0);
        Period periodDiff =new Period(leapday,febof28year2000);
        System.out.println("-----"+periodDiff+"------");

Also if months value is 12, shouldn't it be converted to one year ? 

I tested also with the java.time and I got the expected behavior of 3 years 11 months and 30 days.

        LocalDate today = LocalDate.of(2000, Month.FEBRUARY, 28);
        LocalDate birthday = LocalDate.of(1996, Month.FEBRUARY, 29);

        Period p = Period.between(birthday, today);
        long p2 = ChronoUnit.DAYS.between(birthday, today);
        System.out.println("You are " + p.getYears() + " years, " + p.getMonths()
                + " months, and " + p.getDays()
                + " days old. (" + p2 + " days total)");

**Comment by MenoData** [comment] 2015-06-24 11:37
Sounds like a duplicate of https://github.com/JodaOrg/joda-time/issues/132

**Comment by cage200** [comment] 2015-06-24 11:46
I have seen that one , and does not look similar.The main issue for me is that is returning 12 months.Even if years is not increased, I would have expected to see 11 months and 30 days. Notice that both years are leap years.

**Comment by MenoData** [comment] 2015-06-24 11:59
Okay, not an exact duplicate regarding your input and the use of `DateTime`. By the way, I get 3 years and 12 months, not 13 years and 12 months. Anyway, the underlying period arithmetic is basically the same as described in the issue 132.

**Comment by cage200** [comment] 2015-06-24 12:31
Yeap, my mistake, there are 3 years and not 13. I just corrected.

**Comment by jodastephen** [comment] 2015-10-24 06:55
This is simply how the standard Joda-Time algorithm works. Since it has been that way for a long time, it cannot be changed. Call `normalizedStandard()` on the result to get the output of 4 years.

**Closed by jodastephen** 2015-10-24 06:55 UTC
Labels: NeedsInvestigation

**Comment by visitsb** [comment] 2018-11-29 06:10
Not sure if `normalized()` works as I got the same result. Using `java.time`, I whipped up my own logic that correctly handles calculating age whether leap years or not - this handles any boundary cases correctly & has no performance overhead.
```
public static function getAge(birthDate : LocalDate, targetDate : LocalDate) : int {
  var age : int = 0
  var birthMonthDay : MonthDay = MonthDay.from(birthDate)
  var nextBirthDate : LocalDate = birthMonthDay.atYear(birthDate.Year + 1/*Next year*/)

  // Continue counting age until our next birth date passes target date
  while (nextBirthDate.compareTo(targetDate) <= 0) {
    age++
    nextBirthDate = birthMonthDay.atYear(nextBirthDate.Year + 1/* Next year*/)
  }

  return age
}
```
This would help anyone looking at `joda.time` or `java.time` on Java 8 or above.
