### ISSUE TITLE
MonthDay.plusDays() stucks on February

### ISSUE THREAD

**Issue by nofate** [JodaOrg/joda-time#232] opened 2015-01-30 13:04 UTC
The following Groovy code demontrates the issue:

    import org.joda.time.MonthDay
    println new MonthDay(1, 1).plusDays(59) // prints --02-29
    println new MonthDay(1, 1).plusDays(60) // prints --02-01

At the last line I have expected March 1, not February

**Comment by jodastephen** [comment] 2015-01-30 13:07
Duplicate of #227, fixed in master branch.

**Closed by jodastephen** 2015-01-30 13:07 UTC
Labels: Bug, Fixed
