### ISSUE TITLE
Etc/GMT not recognised as timezone id in 2.9.1

### ISSUE THREAD

**Issue by hearnden** [JodaOrg/joda-time#347] opened 2016-01-20 12:14 UTC
Joda 2.9.1 does not recognize the `Etc/GMT` timezone id.  It does recognise all its aliases, however.  

Sample test case below:
```
public class TestJoda {
 @Test
  public void testEtcGMT() {
    DateTimeFormatter f = DateTimeFormat.forPattern("ZZZ");
    // Test the aliases
    f.parseDateTime("Etc/GMT+0");
    f.parseDateTime("Etc/UTC");
    f.parseDateTime("Greenwich");
    // Test the canonical id
    f.parseDateTime("Etc/GMT");  // <-- This fails
  }
}
```

The `Etc/GMT` timezone is listed as a canonical id here: http://www.joda.org/joda-time/timezones.html

**Comment by hearnden** [comment] 2016-01-20 12:17
Same occurs for a timezone id of `GMT`.

**Comment by jodastephen** [comment] 2016-01-28 13:27
Duplicate of #332

**Closed** 2016-01-28 13:30 UTC
Labels: Bug, Fixed
